### ISSUE TITLE
💡 Metadata for the models

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ersilia-assistant#1]
Hi @DhanshreeA, I am dropping here some thoughts about AI-generated metadata for the models. This is something I would like to lead (with your assistance).

If we are going to do local AI, we need the best-possible metadata for the models, in a relatively well structured way, so that a lightweight LLM can behave properly given a user prompt. For this, I think that the current metadata is not sufficient. Therefore, I suggest that we develop a pipeline to annotate a given model with an AI-generated metadata that can be appended to the current metadata.

I suggest that we develop a python script or command, for example, `model_annotator.py` that does the following:
1. Inputs:
  - A model identifier corresponding to a finalized model repository
  - A PDF of the scientific publication (stored, for instance, in a private S3 bucket)
3. Outputs
  - A well-structured report with, at least, the following chapters
    - Description
    - Publication summary
    - Model architecture summary
    - Training dataset summary
    - Description of the input
    - Description of the output
    - Relevance statement (for example, when would this model be useful?)
    - Model performance and architecture
    - Strengths
    - Limitations
    - About the authors
    - And others... For example, we could think of letting AI come up with the right tags, title and even the slug, which is many times not great as suggested by contributors.
    
More considerations:
- We can use OpenAI GPT-4o (or beyond) for this. This is a one-off query for each model, so not a problem at all. It will not interfere with our goal of having a local LLM.
- Manual review should be done to ensure that this generated metadata is correct. I don't see a problem either, given the rate of incorporation of models into the hub.

@DhanshreeA these are just a few quick thoughts. We can discuss them further.

**Comment by DhanshreeA** [comment]
We now have this in place with both the publications and their summaries uploaded to S3.
